
/**************************************************************
 *	
 *	alertsound, 8 bit, 11025Hz,
 *	1 channel, 19296 bytes/channel
 *	Total Size: 1 * 19296 + 4 (header) = 19340 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\»óÇö\Desktop\alertsound.aiff
 *	Time-stamp: Mon Dec 05 23:33:01 2016
 *	
 **************************************************************/

#ifndef __ALERTSOUNDH__
#define __ALERTSOUNDH__

#define ALERTSOUNDFREQ 11025
#define ALERTSOUNDLEN 19296

extern const unsigned char alertsound[19296];

#endif /* __ALERTSOUNDH__ */
