
/**************************************************************
 *	
 *	callsound, 8 bit, 11025Hz,
 *	1 channel, 34260 bytes/channel
 *	Total Size: 1 * 34260 + 4 (header) = 34304 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\»óÇö\Desktop\callsound.aiff
 *	Time-stamp: Fri Dec 09 16:29:32 2016
 *	
 **************************************************************/

#ifndef __CALLSOUNDH__
#define __CALLSOUNDH__

#define CALLSOUNDFREQ 11025
#define CALLSOUNDLEN 34260

extern const unsigned char callsound[34260];

#endif /* __CALLSOUNDH__ */
