
/**************************************************************
 *	
 *	cheatsound, 8 bit, 11025Hz,
 *	1 channel, 29799 bytes/channel
 *	Total Size: 1 * 29799 + 4 (header) = 29843 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\»óÇö\Desktop\cheatsound.aiff
 *	Time-stamp: Fri Dec 09 14:21:52 2016
 *	
 **************************************************************/

#ifndef __CHEATSOUNDH__
#define __CHEATSOUNDH__

#define CHEATSOUNDFREQ 11025
#define CHEATSOUNDLEN 29799

extern const unsigned char cheatsound[29799];

#endif /* __CHEATSOUNDH__ */
