
/**************************************************************
 *	
 *	codecsound, 8 bit, 11025Hz,
 *	1 channel, 12096 bytes/channel
 *	Total Size: 1 * 12096 + 4 (header) = 12140 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\»óÇö\Desktop\codecsound.aiff
 *	Time-stamp: Mon Dec 05 22:44:51 2016
 *	
 **************************************************************/

#ifndef __CODECSOUNDH__
#define __CODECSOUNDH__

#define CODECSOUNDFREQ 11025
#define CODECSOUNDLEN 12096

extern const unsigned char codecsound[12096];

#endif /* __CODECSOUNDH__ */
