
/**************************************************************
 *	
 *	crashsound, 8 bit, 11025Hz,
 *	1 channel, 120448 bytes/channel
 *	Total Size: 1 * 120448 + 4 (header) = 120492 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\»óÇö\Desktop\crashsound.aiff
 *	Time-stamp: Fri Dec 09 16:24:35 2016
 *	
 **************************************************************/

#ifndef __CRASHSOUNDH__
#define __CRASHSOUNDH__

#define CRASHSOUNDFREQ 11025
#define CRASHSOUNDLEN 120448

extern const unsigned char crashsound[120448];

#endif /* __CRASHSOUNDH__ */
