
/**************************************************************
 *	
 *	instructionstheme, 8 bit, 11025Hz,
 *	1 channel, 351072 bytes/channel
 *	Total Size: 1 * 351072 + 4 (header) = 351116 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\»óÇö\Desktop\instructionstheme.aiff
 *	Time-stamp: Fri Dec 09 16:36:07 2016
 *	
 **************************************************************/

#ifndef __INSTRUCTIONSTHEMEH__
#define __INSTRUCTIONSTHEMEH__

#define INSTRUCTIONSTHEMEFREQ 11025
#define INSTRUCTIONSTHEMELEN 351072

extern const unsigned char instructionstheme[351072];

#endif /* __INSTRUCTIONSTHEMEH__ */
