
/**************************************************************
 *	
 *	level1audio, 8 bit, 11025Hz,
 *	1 channel, 210240 bytes/channel
 *	Total Size: 1 * 210240 + 4 (header) = 210284 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\»óÇö\Desktop\level1audio.aiff
 *	Time-stamp: Sun Dec 04 21:10:44 2016
 *	
 **************************************************************/

#ifndef __LEVEL1AUDIOH__
#define __LEVEL1AUDIOH__

#define LEVEL1AUDIOFREQ 11025
#define LEVEL1AUDIOLEN 210240

extern const unsigned char level1audio[210240];

#endif /* __LEVEL1AUDIOH__ */
