
/**************************************************************
 *	
 *	losetheme, 8 bit, 11025Hz,
 *	1 channel, 45504 bytes/channel
 *	Total Size: 1 * 45504 + 4 (header) = 45548 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\»óÇö\Desktop\losetheme.aiff
 *	Time-stamp: Mon Dec 05 23:30:36 2016
 *	
 **************************************************************/

#ifndef __LOSETHEMEH__
#define __LOSETHEMEH__

#define LOSETHEMEFREQ 11025
#define LOSETHEMELEN 45504

extern const unsigned char losetheme[45504];

#endif /* __LOSETHEMEH__ */
