
/**************************************************************
 *	
 *	openingtheme, 8 bit, 11025Hz,
 *	1 channel, 272160 bytes/channel
 *	Total Size: 1 * 272160 + 4 (header) = 272204 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\»óÇö\Desktop\openingtheme.aiff
 *	Time-stamp: Sun Dec 04 20:51:11 2016
 *	
 **************************************************************/

#ifndef __OPENINGTHEMEH__
#define __OPENINGTHEMEH__

#define OPENINGTHEMEFREQ 11025
#define OPENINGTHEMELEN 272160

extern const unsigned char openingtheme[272160];

#endif /* __OPENINGTHEMEH__ */
