
/**************************************************************
 *	
 *	wintheme, 8 bit, 11025Hz,
 *	1 channel, 79776 bytes/channel
 *	Total Size: 1 * 79776 + 4 (header) = 79820 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\»óÇö\Desktop\wintheme.aiff
 *	Time-stamp: Mon Dec 05 23:23:26 2016
 *	
 **************************************************************/

#ifndef __WINTHEMEH__
#define __WINTHEMEH__

#define WINTHEMEFREQ 11025
#define WINTHEMELEN 79776

extern const unsigned char wintheme[79776];

#endif /* __WINTHEMEH__ */
